MovieRental/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieRental.Models;

namespace MovieRental.Controllers
{
    public class AddressController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: /Address/
        public ActionResult Index()
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(db.Addresses.ToList());
        }

        // GET: /Address/Details/5
        public ActionResult Details(int? id)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // GET: /Address/Create
        public ActionResult Create()
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: /Address/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,AddressStore")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Addresses.Add(address);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(address);
        }

        // GET: /Address/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: /Address/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include= "ID,AddressStore")] Address address)
        {
            if (ModelState.IsValid)
            {
                db.Entry(address).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(address);
        }

        // GET: /Address/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = db.Addresses.Find(id);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        // POST: /Address/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Address address = db.Addresses.Find(id);
            db.Addresses.Remove(address);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult GetAddresses()
        {
            return (Json(db.Addresses.ToList<Address>(),JsonRequestBehavior.AllowGet));   
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieRental/Controllers/TwitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TweetSharp;

namespace MovieRental.Controllers
{
    public class TwitterController : Controller
    {
        private static string key = "8Y1wwVPxhbyIICQ73JlsWZzu8";
        private static string secret = "aYSjGVY5J0mHCCWxqFwSTpVobq2Ro9PbtAVKOfw4bCSnivwvHg";
        private static string access_token = "910513747399266304-oSbBPqz4naZT2cEetLG7V7CvDFfO2YV";
        private static string access_token_secret = "XQMfF6pfgTLKXFnq4QBkKfPEqQjuOANbnERDmTSAM8TrQ";

        TwitterService service = new TwitterService(key, secret, access_token, access_token_secret);

        // GET: Twitter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TwitterCallback(string oauth_token, string oauth_verifier)
        {
            var requesttoken = new OAuthRequestToken { Token = oauth_token };
            try
            {
                VerifyCredentialsOptions option = new VerifyCredentialsOptions();
                TwitterUser user = service.VerifyCredentials(option);

                TempData["Name"] = user.Name;
                TempData["userpic"] = user.ProfileImageUrl;

                return Redirect("http://localhost:14623/Twitter");
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult TwitterAuth()
        {
            OAuthRequestToken requestToken = service.GetRequestToken("http://localhost:14623/Twitter/TwitterCallback");
            Uri uri = service.GetAuthenticationUrl(requestToken);

            return Redirect(uri.ToString());
        }

        public ActionResult TwitterPost(string TeewtText)
        {
            service.SendTweet(new SendTweetOptions { Status = TeewtText } , (tweet, response) => { });

            TwitterUser user = service.VerifyCredentials(new VerifyCredentialsOptions());

            TempData["Name"] = user.Name;
            TempData["userpic"] = user.ProfileImageUrl;

            return Redirect("http://localhost:14623/Twitter");
        }
    }
}

MovieRental/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieRental.Models;

namespace MovieRental.Controllers
{
    public class UsersController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: /Users/
        public ActionResult Index(string username,string email,int? month)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }

            var users = db.Users.AsQueryable();

            if (!String.IsNullOrEmpty(username))
            {
                users = users.Where(u => u.Username.Contains(username));
            }
            if (!String.IsNullOrEmpty(email))
            {
                users = users.Where(u => u.Email.Contains(email));
            }
            if (month != null && month > 0)
            {
                users = users.Where(u => u.BirthDate.Month == month);
            }

            return View(users.ToList());
        }

        // GET: /Users/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["LoggedUserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int userId = Int32.Parse(Session["LoggedUserId"].ToString());
            if (id == null || id != userId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: /Users/Create
        public ActionResult Create()
        {
            if (Session["LoggedUserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        // POST: /Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,FirstName,LastName,BirthDate,Email,Username,Password,IsManager")] User user)
        {
            if (Session["LoggedUserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: /Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,FirstName,LastName,BirthDate,Email,Username,Password,IsManager")] User user)
        {
            if (Session["LoggedUserId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: /Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!(Session["IsManagerLogged"] != null && Session["IsManagerLogged"].ToString().Equals(true.ToString())))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rent A Movie</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var canvas = document.getElementById("logo");
            var ctx = canvas.getContext("2d");

            ctx.rotate(0.05);

            // Create blue rect
            ctx.save();
            ctx.fillStyle = "rgb(13,64,169)";
            ctx.shadowColor = '#999';
            ctx.shadowBlur = 15;
            ctx.shadowOffsetX = 5;
            ctx.shadowOffsetY = 5;
            ctx.fillRect(0, 0, 190, 100);
            ctx.restore();

            // Create yellow outline
            grd = ctx.createLinearGradient(0.000, 150.000, 300.000, 150.000);
            grd.addColorStop(0.4, 'rgba(255, 255, 0, 1.000)');
            grd.addColorStop(0.8, 'rgba(255, 255, 255, 1.000)');
            ctx.strokeStyle = grd;
            ctx.lineWidth = 1.5;
            ctx.strokeRect(25, 10, 165, 80);

            // Blue line to cover one of the outline sides
            ctx.strokeStyle = "rgb(13,64,169)";
            ctx.beginPath();
            ctx.lineWidth = 2;
            ctx.moveTo(190, 0);
            ctx.lineTo(190, 100);
            ctx.stroke();

            // White circle
            ctx.fillStyle = "rgb(255,255,255)";
            ctx.beginPath();
            ctx.arc(5, 50, 15, 0, Math.PI * 2, true);
            ctx.fill();

            // Font
            ctx.font = "25px Comic Sans MS";
            ctx.fillStyle = "rgb(243,222,62)";
            ctx.fillText("Rent", 50, 45);
            ctx.fillText("A Movie", 70, 75);
        });
    </script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <header>
        <div style="float: left;  left:70px; position:relative">
            <canvas id="logo"></canvas>
        </div>
    </header>
    <br />
    <br />
    <br />
    <nav>
        <ul class="nav nav-pills">
            <li class="pull-right" style="width:50px">&nbsp;</li>
            <li>@Html.ActionLink("Home", "Index", "Home", null, null)</li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    Genres <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    @{Html.RenderAction("GenreMenu", "Home");}
                </ul>
            </li>
            @if (Session["LoggedUserId"] == null)
            {
                <li class="pull-right">@Html.ActionLink("Sign up", "Create", "Users", null, null)</li>
                <li class="active pull-right">@Html.ActionLink("Login", "Login", "Home", null, null)</li>
            }
            else
            {
                if (Session["IsManagerLogged"] == true.ToString())
                {
                    <li>@Html.ActionLink("Users", "Index", "Users", null, null)</li>
                    <li>@Html.ActionLink("Orders", "Index", "Orders", null, null)</li>
                    <li>@Html.ActionLink("Addresses", "Index", "Address", null, null)</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("movie by genre", "Report", "Home", null, null)</li>
                            <li>@Html.ActionLink("orders by genre", "ReportOrdersByGenre", "Home", null, null)</li>
                            <li>@Html.ActionLink("orders by date", "ReportOrdersByDate", "Home", null, null)</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Twitter Manager", "TwitterAuth", "Twitter", null, null)</li>
                }
                <li class="active pull-right">@Html.ActionLink("Log-out", "LogOut", "Home", null, null)</li>
                <li class="pull-right">@Html.ActionLink("My Profile", "Details", "Users", new { id = Session["LoggedUserId"] }, null)</li>
                <li class="pull-right">@Html.ActionLink("My Orders", "Details", "Orders", null, null)</li>
            }
            <li>@Html.ActionLink("About Us", "AboutUs", "Home", null, null)</li>
        </ul>
    </nav>
    <article>
        <section id="content" class="container body-content">
            @RenderBody()
        </section>
    </article>
    <hr />
    <footer>
        &copy; @DateTime.Now.Year - Lavi Bursuk, Tamir Yardeni & Naor Twig
    </footer>
</body>
</html>